# Generated by Django 6.0.4 on 2026-04-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-published_at", "-created_at"],
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="meta_description",
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
    ]
