# Generated by Django 6.0.4 on 2026-04-27 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_options_alter_post_meta_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-published_on", "-created_on"],
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="created_on",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="updated_at",
            new_name="last_modified",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="published_at",
            new_name="published_on",
        ),
    ]
