# Generated by Django 6.0.4 on 2026-04-27 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipes", "0009_alter_recipe_garnishes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "filter_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COCKTAIL", "Cocktail"),
                            ("MOCKTAIL", "Mocktail"),
                            ("COFFEE", "Coffee"),
                            ("TEA", "Tea"),
                        ],
                        help_text="Filter by drink category (Cocktail/Mocktail etc.)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "filter_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SHAKEN", "Shaken"),
                            ("STIRRED", "Stirred"),
                            ("BUILT, Built", "Built"),
                            ("BLENDED", "Blended"),
                        ],
                        help_text="Filter by preparation method (Shaken/Stirred/Built etc.)",
                        max_length=128,
                        null=True,
                    ),
                ),
                ("total_questions", models.PositiveSmallIntegerField()),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("is_complete", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "filter_ingredient_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Filter recipes that contain at least one ingredient from this category.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz_sessions",
                        to="recipes.ingredientcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Session",
                "verbose_name_plural": "Quiz Sessions",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("ingredients", "What's in this cocktail?"),
                            ("amount", "How much of this ingredient?"),
                            ("negative", "Which is NOT an ingredient?"),
                        ],
                        max_length=32,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("answered", models.BooleanField(default=False)),
                ("answered_correctly", models.BooleanField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        help_text="The recipe this question is about.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_questions",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "target_ingredient",
                    models.ForeignKey(
                        blank=True,
                        help_text="For AMOUNT question type only — the specific ingredient being asked about.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recipes.ingredient",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quizzes.quizsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Question",
                "verbose_name_plural": "Quiz Questions",
                "ordering": ["order"],
                "unique_together": {("session", "order")},
            },
        ),
        migrations.CreateModel(
            name="QuizChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_text", models.CharField(max_length=256)),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="quizzes.quizquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Choice",
                "verbose_name_plural": "Quiz Choices",
                "ordering": ["order"],
                "unique_together": {("question", "order")},
            },
        ),
    ]
