# Generated by Django 6.0.4 on 2026-04-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizsession",
            name="filter_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SHAKEN", "Shaken"),
                    ("STIRRED", "Stirred"),
                    ("BUILT", "Built"),
                    ("BLENDED", "Blended"),
                ],
                help_text="Filter by preparation method (Shaken/Stirred/Built etc.)",
                max_length=128,
                null=True,
            ),
        ),
    ]
