# Generated by Django 6.0.4 on 2026-04-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="recipes.tag"
            ),
        ),
    ]
