# Generated by Django 6.0.4 on 2026-04-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipe_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeingredient",
            name="amount",
        ),
    ]
