# Generated by Django 6.0.4 on 2026-04-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_garnish_recipe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="garnish",
            name="recipe",
        ),
        migrations.AddField(
            model_name="garnish",
            name="recipe",
            field=models.ManyToManyField(to="recipes.recipe"),
        ),
    ]
