# Generated by Django 6.0.4 on 2026-04-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_remove_recipeingredient_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="cateogory",
            new_name="category",
        ),
    ]
