# Generated by Django 4.1.1 on 2026-04-10 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_remove_garnish_recipe_garnish_recipe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="garnish",
            name="recipe",
        ),
        migrations.CreateModel(
            name="RecipeGarnish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "garnish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.garnish",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="garnishes",
            field=models.ManyToManyField(
                related_name="recipes",
                through="recipes.RecipeGarnish",
                to="recipes.garnish",
            ),
        ),
    ]
