# Generated by Django 6.0.4 on 2026-04-10 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_remove_garnish_recipe_recipegarnish_recipe_garnishes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipegarnish",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_garnishes",
                to="recipes.recipe",
            ),
        ),
    ]
