# Generated by Django 6.0.4 on 2026-04-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_recipeingredient_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="alt_glasses",
            field=models.ManyToManyField(
                blank=True,
                related_name="alt_recipes",
                to="recipes.glasstype",
                verbose_name="Alternative Glasses",
            ),
        ),
    ]
