# Generated by Django 6.0.4 on 2026-04-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_recipegarnish_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipegarnish",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
