# Generated by Django 6.0.4 on 2026-04-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_recipegarnish_is_primary"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Garnish",
            new_name="GarnishType",
        ),
    ]
