# Generated by Django 6.0.4 on 2026-04-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_recipe_alt_glasses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="tags",
                to="recipes.tag",
                verbose_name="Recipe Tags",
            ),
        ),
    ]
