# Generated by Django 6.0.4 on 2026-04-10 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_rename_garnish_garnishtype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipegarnish",
            old_name="garnish",
            new_name="garnish_type",
        ),
    ]
