# Generated by Django 6.0.4 on 2026-04-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_alter_recipe_tags"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GlassType",
            new_name="Vessel",
        ),
        migrations.AlterModelOptions(
            name="vessel",
            options={
                "ordering": ("created_on",),
                "verbose_name": "Vessel (Glass/Cup)",
                "verbose_name_plural": "Vessels (Glasses/Cups)",
            },
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="primary_glass",
            new_name="primary_vessel",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="alt_glasses",
        ),
        migrations.AddField(
            model_name="recipe",
            name="alt_vessels",
            field=models.ManyToManyField(
                blank=True,
                related_name="alt_recipes",
                to="recipes.vessel",
                verbose_name="Alternative Vessels",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("COCKTAIL", "Cocktail"),
                    ("MOCKTAIL", "Mocktail"),
                    ("COFFEE", "Coffee"),
                    ("TEA", "Tea"),
                ],
                default="COCKTAIL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="serving_temperature",
            field=models.CharField(
                choices=[
                    ("HOT", "Hot"),
                    ("COLD", "Cold"),
                    ("ROOM", "Room Temperature"),
                    ("FROZEN", "Frozen/Blended"),
                ],
                default=None,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipe",
            name="method",
            field=models.CharField(
                choices=[
                    ("SHAKEN", "Shaken"),
                    ("STIRRED", "Stirred"),
                    ("BUILT, Built", "Built"),
                    ("BLENDED", "Blended"),
                ],
                default="BUILT, Built",
                max_length=128,
            ),
        ),
    ]
