# Generated by Django 6.0.4 on 2026-04-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_rename_glasstype_vessel_alter_vessel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="garnishes",
            field=models.ManyToManyField(
                blank=True,
                related_name="recipes",
                through="recipes.RecipeGarnish",
                to="recipes.garnishtype",
            ),
        ),
    ]
