# Generated by Django 6.0.4 on 2026-04-27 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_alter_recipe_garnishes"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredientcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcategories",
                to="recipes.ingredientcategory",
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="measurement_unit",
            field=models.CharField(
                choices=[
                    ("ML", "Millilitres"),
                    ("DASH", "Dash"),
                    ("DROP", "Drop"),
                    ("BARSPOON", "Bar Spoon"),
                    ("WHOLE", "Whole"),
                ],
                default="ML",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipe",
            name="method",
            field=models.CharField(
                choices=[
                    ("SHAKEN", "Shaken"),
                    ("STIRRED", "Stirred"),
                    ("BUILT", "Built"),
                    ("BLENDED", "Blended"),
                ],
                default="BUILT",
                max_length=128,
            ),
        ),
    ]
