# Generated by Django 6.0.4 on 2026-04-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_ingredientcategory_parent_recipeingredient_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeingredient",
            name="ml_amount",
        ),
    ]
