# Generated by Django 6.0.4 on 2026-04-27 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_remove_recipeingredient_ml_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="recipes.ingredientcategory",
                verbose_name="parent",
            ),
        ),
    ]
